### ISSUE TITLE
broke theme

### ISSUE THREAD

**Issue by xavierartot** [bigwilliam/sage-reloaded#2]
Hi,
I want to give a try to your work, but the them is broke.
Thanks

**Comment by cobbman** [comment]
Hi @xavierartot - can you please be more specific? We still use this theme currently and it works for us. Can you tell me specifically what you tried?

**Comment by xavierartot** [comment]
Sorry I forgot to configure the manifest...

**Comment by cobbman** [comment]
Okay no problem.
